const initState = {
  cars: [],
  feature: [
    "Air Conditioning",
    "GPS Navigation",
    "Bluetooth",
    "Backup Camera",
    "Heated Seats",
    "Sunroof",
  ],
  brand: [
    "BMW",
    "AUDI",
    "MERCEDES",
    "PORSCHE",
    "TOYOTA",
    "VW",
    "VOLVO",
    "FORD",
    "NISSAN",
    "HONDA",
    "KIA",
    "LEXUS",
    "SUBARU",
    "MITSUBISHI",
    "CHEVROLET",
    "DODGE",
    "FERRARI",
    "LAMBORGHINI",
    "JAGUAR",
    "MASERATI",
    "ROLLS-ROYCE",
    "TESLA",
    "PEUGEOT",
    "FIAT",
    "HYUNDAI",
    "RENAULT",
    "LAND ROVER",
    "BUGATTI",
    "BENTLEY",
    "ASTON MARTIN",
    "ALFA ROMEO",
    "CITROËN",
    "ACURA",
    "INFINITI",
    "LINCOLN",
    "SAAB",
    "SKODA",
    "SEAT",
    "HUMMER",
    "MCLAREN",
    "MAYBACH",
    "PONTIAC",
    "CHRYSLER",
    "ISUZU",
    "GMC",
    "JEEP",
    "CADILLAC",
    "BUICK",
    "MINI",
    "SUZUKI",
    "MAZDA",
    "RAM",
    "SCION",
    "SRT",
    "GENESIS",
    "OPEL",
    "HOLDEN",
    "DAEWOO",
    "SSANGYONG",
    "TATA",
    "MAHINDRA",
    "LADA",
    "LOTUS",
    "SATURN",
    "PLYMOUTH",
    "AMC",
    "YUGO",
    "MG",
    "AIXAM",
    "DATSUN",
  ],
  specification: [],
  category: [
    "Sedan",
    "SUV",
    "Truck",
    "Van",
    "Coupe",
    "Convertible",
    "Electric",
    "Sports",
    "Luxury",
    "Economy",
  ],
};
const CarsReducer = (state = initState, action) => {
  switch (action.type) {
    case "ADD_CAR":
      return {
        ...state,
        cars: [...state.cars, action.payload],
      };
    default:
      return state;
  }
};
export default CarsReducer;
